import { Repository } from "../../data/types";

const mockRepositories = [
  {
    id: 528339561,
    language: "TypeScript",
    htmlUrl:
      "https://github.com/total-typescript/beginners-typescript-tutorial",
    name: "beginners-typescript-tutorial",
    description: "An interactive TypeScript tutorial for beginners",
    stargazersCount: 2571,
    isStargazed: true,
  },
  {
    id: 527719753,
    language: "C++",
    htmlUrl: "https://github.com/cemu-project/Cemu",
    name: "Cemu",
    description: "Cemu is a Wii U emulator",
    stargazersCount: 2253,
    isStargazed: false,
  },
  {
    id: 527519851,
    language: "JavaScript",
    htmlUrl: "https://github.com/itorr/sakana",
    name: "sakana",
    description: "🐟「Sakana!」石蒜虚拟器",
    stargazersCount: 910,
    isStargazed: false,
  },
  {
    id: 527583905,
    language: "Java",
    htmlUrl: "https://github.com/runsidekick/sidekick",
    name: "sidekick",
    description:
      "Free and open-source live application debugger. Like chrome dev tools but for your backend",
    stargazersCount: 825,
    isStargazed: false,
  },
  {
    id: 528823499,
    language: "Rust",
    htmlUrl: "https://github.com/ihciah/shadow-tls",
    name: "shadow-tls",
    description: null,
    stargazersCount: 478,
    isStargazed: false,
  },
  {
    id: 528152092,
    language: "HTML",
    htmlUrl: "https://github.com/cmdr2/stable-diffusion-ui",
    name: "stable-diffusion-ui",
    description:
      "A simple way to install and use Stable Diffusion on your own computer. Provides a browser UI for generating images from text prompts and images. Just enter your text prompt, and see the generated image.",
    stargazersCount: 286,
    isStargazed: false,
  },
  {
    id: 528313152,
    language: "JavaScript",
    htmlUrl: "https://github.com/benphelps/homepage",
    name: "homepage",
    description:
      "A highly customizable homepage (or startpage / application dashboard) with Docker and service API integrations.",
    stargazersCount: 277,
    isStargazed: false,
  },
  {
    id: 527767366,
    language: "HTML",
    htmlUrl:
      "https://github.com/digitalinnovationone/semana-frontend-mundo-invertido",
    name: "semana-frontend-mundo-invertido",
    description:
      "Página com theme switcher utilizando HTML, CSS e JavaScript, além de integrar um formulário de inscrição com um banco de dados Firebase.",
    stargazersCount: 255,
    isStargazed: false,
  },
  {
    id: 527419188,
    language: "Python",
    htmlUrl: "https://github.com/limoest/daily_reminder",
    name: "daily_reminder",
    description: "微信公众号全自动每日推送（先看README.md里的内容）",
    stargazersCount: 214,
    isStargazed: false,
  },
  {
    id: 527591471,
    language: "Python",
    htmlUrl: "https://github.com/AUTOMATIC1111/stable-diffusion-webui",
    name: "stable-diffusion-webui",
    description: "Stable Diffusion web UI",
    stargazersCount: 170,
    isStargazed: false,
  },
  {
    id: 528955000,
    language: "Python",
    htmlUrl: "https://github.com/jquesnelle/txt2imghd",
    name: "txt2imghd",
    description: "A port of GOBIG for Stable Diffusion",
    stargazersCount: 157,
    isStargazed: false,
  },
  {
    id: 528687234,
    language: "Python",
    htmlUrl: "https://github.com/lucidrains/Adan-pytorch",
    name: "Adan-pytorch",
    description:
      "Implementation of the Adan (ADAptive Nesterov momentum algorithm) Optimizer in Pytorch",
    stargazersCount: 118,
    isStargazed: false,
  },
  {
    id: 528111216,
    language: "Python",
    htmlUrl: "https://github.com/sec-an/TV_Spider",
    name: "TV_Spider",
    description:
      "TVBoxOSC 服务端爬虫 Custom Server Spider for Tv Written in Python3",
    stargazersCount: 111,
    isStargazed: false,
  },
  {
    id: 529275861,
    language: null,
    htmlUrl: "https://github.com/DmitryScaletta/free-heroku-alternatives",
    name: "free-heroku-alternatives",
    description:
      "Comparison of free Heroku alternatives for backend applications",
    stargazersCount: 110,
    isStargazed: false,
  },
  {
    id: 529029423,
    language: "Ruby",
    htmlUrl: "https://github.com/hopsoft/turbo_ready",
    name: "turbo_ready",
    description: "Take full control of the DOM with Turbo Streams",
    stargazersCount: 104,
    isStargazed: false,
  },
  {
    id: 529588220,
    language: "Rust",
    htmlUrl: "https://github.com/sudeep9/mojo",
    name: "mojo",
    description: "Versioning filesystem for Sqlite",
    stargazersCount: 104,
    isStargazed: false,
  },
  {
    id: 528287312,
    language: "Lua",
    htmlUrl: "https://github.com/unkperson/player-model-changer",
    name: "player-model-changer",
    description: "💉: gamesense lua script to change local player model",
    stargazersCount: 102,
    isStargazed: false,
  },
  {
    id: 529026060,
    language: "C++",
    htmlUrl: "https://github.com/Kudaes/Elevator",
    name: "Elevator",
    description: "UAC Bypass by abusing RPC and debug objects.",
    stargazersCount: 95,
    isStargazed: false,
  },
  {
    id: 529222779,
    language: null,
    htmlUrl: "https://github.com/boyney123/awesome-event-patterns",
    name: "awesome-event-patterns",
    description:
      "Personal collection of links, videos and things to help with event architecture event patterns.",
    stargazersCount: 91,
    isStargazed: false,
  },
  {
    id: 528286745,
    language: "C",
    htmlUrl: "https://github.com/theori-io/CVE-2022-32250-exploit",
    name: "CVE-2022-32250-exploit",
    description: null,
    stargazersCount: 85,
    isStargazed: false,
  },
  {
    id: 527859149,
    language: "C#",
    htmlUrl: "https://github.com/daem0nc0re/TangledWinExec",
    name: "TangledWinExec",
    description:
      "C# PoCs for investigation of Windows process execution techniques investigation",
    stargazersCount: 84,
    isStargazed: false,
  },
  {
    id: 528101408,
    language: "PureScript",
    htmlUrl: "https://github.com/aristanetworks/purescript-backend-optimizer",
    name: "purescript-backend-optimizer",
    description:
      "Optimizing backend toolkit and modern ECMAScript backend for PureScript",
    stargazersCount: 84,
    isStargazed: false,
  },
  {
    id: 529675941,
    language: "Go",
    htmlUrl: "https://github.com/kahroba-lang/kahroba",
    name: "kahroba",
    description:
      "Kahroba is a programming language with educational purposes written in Go",
    stargazersCount: 84,
    isStargazed: false,
  },
  {
    id: 528738725,
    language: null,
    htmlUrl: "https://github.com/sn00pyd0g3/wechat-export",
    name: "wechat-export",
    description: "获取微信聊天记录数据库密钥并导出聊天记录，各版本通用。",
    stargazersCount: 83,
    isStargazed: false,
  },
  {
    id: 528114437,
    language: "Swift",
    htmlUrl: "https://github.com/soulverteam/SoulverStringParsing",
    name: "SoulverStringParsing",
    description:
      'Learn about how SoulverCore can give Swift "better than regex" data parsing features (for many common tasks)',
    stargazersCount: 83,
    isStargazed: false,
  },
  {
    id: 528182874,
    language: null,
    htmlUrl: "https://github.com/CodingForCrypt0/pancakeswap-sniper-bot",
    name: "pancakeswap-sniper-bot",
    description:
      "Pancakeswap Sniper Bot based on BSC. Autobuy, autosell, custom gas fee, coolest interface ever and more, more, more. I also trying to upload new versions of this program every week, to make fewer bugs & etc. You can enjoy this by clicking star.",
    stargazersCount: 83,
    isStargazed: false,
  },
  {
    id: 528629042,
    language: null,
    htmlUrl: "https://github.com/altryne/awesome-ai-art-image-synthesis",
    name: "awesome-ai-art-image-synthesis",
    description:
      "A list of awesome tools, ideas, prompt engineering tools, colabs, models, and helpers for the prompt designer playing with aiArt and image synthesis. Covers Dalle2, MidJourney, StableDiffusion, and open source tools.",
    stargazersCount: 81,
    isStargazed: false,
  },
  {
    id: 527726416,
    language: "JavaScript",
    htmlUrl: "https://github.com/jiawei-zhang-a/Course-Management-System",
    name: "Course-Management-System",
    description: null,
    stargazersCount: 79,
    isStargazed: false,
  },
  {
    id: 529217861,
    language: "C",
    htmlUrl: "https://github.com/p4nic4ttack/doom-flipper-zero",
    name: "doom-flipper-zero",
    description: "Doom Flipper Zero edition",
    stargazersCount: 77,
    isStargazed: false,
  },
  {
    id: 527849461,
    language: "C++",
    htmlUrl: "https://github.com/ORCx41/EtwSessionHijacking",
    name: "EtwSessionHijacking",
    description: "A Poc on blocking Procmon from monitoring network events",
    stargazersCount: 74,
    isStargazed: false,
  },
] as Repository[];

export default mockRepositories;
